# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-28 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(db_index=True),
        ),
    ]
