# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-28 02:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20170127_2109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='start_day',
            new_name='startDay',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start_time',
            new_name='startTime',
        ),
        migrations.AddField(
            model_name='event',
            name='addedAt',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 1, 28, 2, 13, 34, 340883, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='lastEditedAt',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 1, 28, 2, 13, 40, 53375, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
