# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-28 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20170127_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='endDay',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='endTime',
            field=models.TimeField(blank=True, db_index=True, null=True),
        ),
    ]
