# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-28 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20170127_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
