# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-28 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='announcementWebsite',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='buildingRoom',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='fbEventLink',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='primaryContactEmail',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='primaryContactName',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='sponsors',
            field=models.TextField(blank=True),
        ),
    ]
