# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-28 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20170128_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='gobblerConnectLink',
            field=models.URLField(blank=True),
        ),
    ]
