# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 21:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addedAt', models.DateTimeField(auto_now_add=True, verbose_name='Added on')),
                ('lastEditedAt', models.DateTimeField(auto_now=True, verbose_name='Last Edit on')),
                ('currentlyActive', models.BooleanField(default=True, verbose_name='This organization is currently operating')),
                ('orgName', models.CharField(max_length=200, verbose_name='Organization Name')),
                ('description', models.TextField(blank=True, verbose_name='Organization Description')),
                ('descriptionApproved', models.BooleanField(default=False, verbose_name='Description has been approved by the organization')),
                ('affilatedVT', models.BooleanField(default=False, verbose_name='This organization has a formal affiliation with Virginia Tech')),
                ('contactEmail', models.CharField(blank=True, max_length=200, verbose_name='Contact Email')),
                ('contactPhone', models.CharField(blank=True, max_length=200, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '999-999-9999'. Up to 15 digits allowed.", regex='^\\d{3}-\\d{3}-\\d{4}$')], verbose_name='Contact Phone Numbers')),
                ('facebookPage', models.URLField(blank=True, verbose_name='Organization Facebook page')),
                ('website', models.URLField(blank=True, verbose_name='Organization Website')),
            ],
        ),
    ]
