# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='twitter',
            field=models.URLField(blank=True, verbose_name='Organization Twitter'),
        ),
        migrations.AddField(
            model_name='organization',
            name='youtube',
            field=models.URLField(blank=True, verbose_name='Organization YouTube'),
        ),
    ]
