# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-22 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addedAt', models.DateTimeField(auto_now_add=True, verbose_name='Added on')),
                ('lastEditedAt', models.DateTimeField(auto_now=True, verbose_name='Last Edit on')),
                ('eventDay', models.DateField(db_index=True, verbose_name='Event Day')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('sameDayOrder', models.IntegerField(blank=True, verbose_name='Order for same day events')),
            ],
        ),
    ]
