# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-22 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='sameDayOrder',
            field=models.IntegerField(blank=True, null=True, verbose_name='Order for same day events'),
        ),
    ]
